### PR TITLE
New Languages

### PR DESCRIPTION
**Pull request by Dekserrrrrr**
-Removes Sinta'unathi and Sinta'azaziba
-Adds 3 new Unathi languages (work in progress)
-Removes Tradeband, Sol Common, Freespeak and Tau Ceti Basic
-Adds English, Lunian, New Mandarin and Martian.
-Remove old Tajara languages and add new ones.
-Remove old Skrell language, possibly forever or add a new one.
-Add a new Vaurca language, visual based for quick, silent communication that doesn't alert every bug on the map.

### CODE REVIEW

**Comment by CrowOfBourbon** [comment]
Is this ready for a merge?

**Comment by Dekserrrrrr** [comment]
Nah.

**Comment by Dekserrrrrr** [comment]
Probably going to work on this overnight.

**Comment by Eyeveri** [comment]
Status of this?

**Comment by Dekserrrrrr** [comment]
With the last 1/2 PR's this should finish languages.

**Comment by Dekserrrrrr** [comment]
Yeah so my coding setup is fucked and I'm moving into having almost no time for work anyways. This is good to merge but there is a known issue with this that I'll pop on the tracker, it doesn't cause errors but basically destroys hivenet.

**Pull request merged**
